#!/bin/sh
# Need sh, not bash, otherwise GitHub Desktop on Windows produces a "cannot spawn" error.

script="$(dirname "${0}")/lint-hook.sh"

log() {
	echo "${0}: ${@}" >&2
}

log "Current platform: $(uname)"

if [ "$(uname -o)" == 'Msys' ]; then
	bash='/c/Program Files/Git/bin/bash.exe'
	if [ ! -f "${bash}" ]; then
		log "Could not find bash at '${bash}'."
		log 'Please ensure that Git Bash is installed.'
		exit 1
	fi
	"${bash}" "${script}"
else
	"${script}"
fi
